# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddAS.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addAS(object):
    def setupUi(self, addAS):
        addAS.setObjectName("addAS")
        addAS.resize(767, 493)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AIM.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addAS.setWindowIcon(icon)
        addAS.setStyleSheet("Background:rgb(0, 0, 83);\n"
"color:White")
        self.centralwidget = QtWidgets.QWidget(addAS)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setObjectName("header")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.header)
        self.label.setMinimumSize(QtCore.QSize(200, 100))
        self.label.setMaximumSize(QtCore.QSize(100, 200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("AIM.JPG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gp_title = QtWidgets.QLabel(self.header)
        self.gp_title.setStyleSheet("\n"
"    font: 75 20pt \"Rockwell\";\n"
"    color: white;\n"
"    border-radius:20px;\n"
"    text-align:left;\n"
"    padding-left:5px;\n"
"    padding-right:5px;")
        self.gp_title.setObjectName("gp_title")
        self.verticalLayout_2.addWidget(self.gp_title)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.header)
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setStyleSheet("QLineEdit,QDateEdit,QComboBox,QSpinBox{\n"
"    height:30px;\n"
"    font: 75 8pt \"System\";\n"
"border:none;\n"
"border-bottom:2px solid gray\n"
"}\n"
"QPushButton{\n"
"    height:30px;\n"
"    border-radius:10;\n"
"    font: 75 8pt \"System\";\n"
"}\n"
"QLabel{\n"
"    height:30px;\n"
"    font: 75 8pt \"System\";\n"
"}\n"
"")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setHorizontalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridWidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.pb_addAS_retour = QtWidgets.QPushButton(self.gridWidget)
        self.pb_addAS_retour.setStyleSheet("border:2px solid rgb(0, 0, 83);\n"
"color:rgb(0, 0, 83);\n"
"border-radius:10px;\n"
"padding:5px;\n"
"background:white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Gestion du personnel/FLS01315.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_addAS_retour.setIcon(icon1)
        self.pb_addAS_retour.setIconSize(QtCore.QSize(32, 32))
        self.pb_addAS_retour.setObjectName("pb_addAS_retour")
        self.gridLayout.addWidget(self.pb_addAS_retour, 5, 2, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_2.setStyleSheet("width:200px;\n"
"background:rgb(0, 85, 255);\n"
"color:white;\n"
"border:2px solid white")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 4, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.gridWidget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        addAS.setCentralWidget(self.centralwidget)

        self.retranslateUi(addAS)
        QtCore.QMetaObject.connectSlotsByName(addAS)

    def retranslateUi(self, addAS):
        _translate = QtCore.QCoreApplication.translate
        addAS.setWindowTitle(_translate("addAS", "Avance Spéciale"))
        self.gp_title.setText(_translate("addAS", "Nouvelle Avance Spéciale"))
        self.label_3.setText(_translate("addAS", "MOTIF :"))
        self.label_5.setText(_translate("addAS", "MONTANT MENSUALITE :"))
        self.label_4.setText(_translate("addAS", "MONTANT TOTAL :"))
        self.label_6.setText(_translate("addAS", "NBR DE MENSUALITE :"))
        self.label_2.setText(_translate("addAS", "PERSONNEL :"))
        self.label_7.setText(_translate("addAS", "DATE DE DEBUT :"))
        self.pb_addAS_retour.setText(_translate("addAS", "Retour"))
        self.pushButton_2.setText(_translate("addAS", "Valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addAS = QtWidgets.QMainWindow()
    ui = Ui_addAS()
    ui.setupUi(addAS)
    addAS.show()
    sys.exit(app.exec_())
