# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AIM.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 666)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AIM.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(3.0)
        MainWindow.setStyleSheet("background:rgb(255, 255, 255);\n"
"font-family:Rockwell")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#header, #footer{\n"
"    background:rgb(0, 0, 70);\n"
"\n"
"    }\n"
"QWidget {\n"
"    height: 150px;\n"
"    border:0px solid red;\n"
"}\n"
"QLabel {\n"
"    border:0px solid red;\n"
"}\n"
"\n"
"#widget_connexion {\n"
"    border-radius:25px;\n"
"}\n"
"\n"
"#body{\n"
"    background:rgb(0, 0, 83)\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.footer = QtWidgets.QWidget(self.centralwidget)
        self.footer.setStyleSheet("")
        self.footer.setObjectName("footer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.footer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.body = QtWidgets.QWidget(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body.sizePolicy().hasHeightForWidth())
        self.body.setSizePolicy(sizePolicy)
        self.body.setMinimumSize(QtCore.QSize(855, 625))
        self.body.setStyleSheet("")
        self.body.setObjectName("body")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalWidget = QtWidgets.QWidget(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setMinimumSize(QtCore.QSize(337, 322))
        self.verticalWidget.setStyleSheet("border:1px solid rgb(0, 0, 83);\n"
"background:none;\n"
"\n"
"")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(320, 128))
        self.label_6.setMaximumSize(QtCore.QSize(330, 128))
        self.label_6.setStyleSheet("background:rgb(0,0,83);\n"
"color:rgb(255, 255, 255);\n"
"border-radius:50px;\n"
"font: 75 22pt \"Rockwell\";\n"
"")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setIndent(0)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setMinimumSize(QtCore.QSize(292, 170))
        self.label.setMaximumSize(QtCore.QSize(330, 170))
        self.label.setStyleSheet("background:rgb(0,0,83);\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("AIM.JPG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.verticalWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.widget_connexion = QtWidgets.QWidget(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_connexion.sizePolicy().hasHeightForWidth())
        self.widget_connexion.setSizePolicy(sizePolicy)
        self.widget_connexion.setMinimumSize(QtCore.QSize(366, 605))
        self.widget_connexion.setMaximumSize(QtCore.QSize(476, 605))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(False)
        font.setWeight(50)
        self.widget_connexion.setFont(font)
        self.widget_connexion.setStyleSheet("\n"
"QLabel {\n"
"    text-align:center;\n"
"    font-size:16px;\n"
"    color:rgb(94, 94, 94)\n"
"}\n"
"QLineEdit {\n"
"    border-radius:10px;\n"
"    font-size:14px;\n"
"    border:2px solid rgb(0, 0, 98);\n"
"    height:40px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border:2px solid rgb(0, 170,0 );\n"
"\n"
"}\n"
"QPushButton {\n"
"    font-size:14px;\n"
"    color:white;\n"
"    border-radius:20px;\n"
"    width:200px;\n"
"    height:40px;\n"
"    \n"
"    background:rgb(0, 0, 98);\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(0, 170, 0);\n"
"    \n"
"}\n"
"*{\n"
"    font-family:Rockwell;\n"
"}")
        self.widget_connexion.setObjectName("widget_connexion")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_connexion)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.widget_connexion)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.user_input = QtWidgets.QLineEdit(self.widget_connexion)
        self.user_input.setAlignment(QtCore.Qt.AlignCenter)
        self.user_input.setObjectName("user_input")
        self.verticalLayout_2.addWidget(self.user_input)
        self.label_4 = QtWidgets.QLabel(self.widget_connexion)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.mdp_input = QtWidgets.QLineEdit(self.widget_connexion)
        self.mdp_input.setAlignment(QtCore.Qt.AlignCenter)
        self.mdp_input.setObjectName("mdp_input")
        self.verticalLayout_2.addWidget(self.mdp_input)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.ConnectButton = QtWidgets.QPushButton(self.widget_connexion)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout_2.addWidget(self.ConnectButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.widget_connexion)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.widget_connexion)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.widget_connexion.raise_()
        self.verticalWidget.raise_()
        self.verticalLayout_3.addWidget(self.body)
        self.label_7 = QtWidgets.QLabel(self.footer)
        self.label_7.setStyleSheet("background:rgb(0, 0, 70);\n"
"color:white;\n"
"font-size:14px")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AIM-LOGIN"))
        self.label_6.setText(_translate("MainWindow", "Appareillage Industriel de Madagascar"))
        self.label_3.setText(_translate("MainWindow", "Nom d\'utilisateur :"))
        self.label_4.setText(_translate("MainWindow", "Mot de passe :"))
        self.ConnectButton.setText(_translate("MainWindow", "Se connecter"))
        self.label_5.setText(_translate("MainWindow", "Appareillage Industriel de Madagascar"))
        self.label_7.setText(_translate("MainWindow", "© Hopes-2024"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())