# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AtelierHome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(1215, 515)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AIM.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow2.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setStyleSheet("background:rgb(0, 0, 83)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.body = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body.sizePolicy().hasHeightForWidth())
        self.body.setSizePolicy(sizePolicy)
        self.body.setStyleSheet("")
        self.body.setObjectName("body")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_3.setContentsMargins(100, 50, 100, 50)
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.body)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("Color:white;\n"
"font: 22pt \"OCR A Extended\";")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.body)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("AIM.JPG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridWidget = QtWidgets.QWidget(self.body)
        self.gridWidget.setStyleSheet("QPushButton{\n"
"    background-color:rgb(170, 170, 255);\n"
"    border-radius:10px;\n"
"    height:40px;\n"
"    width:220px;\n"
"    color:rgb(0, 0,83);\n"
"    font: 75 12pt \"Rockwell\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(228, 231, 255);\n"
"    \n"
"}\n"
"#buttonExit{\n"
"width:100px;\n"
"}")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridWidget)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("AND02220OpérationFinacière.png"))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("LCD15220GestionPersonnel.png"))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("SXP16132Atelier.png"))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridWidget)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("FLS12414EnergyRenouvelable.png"))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.ouvrirGP = QtWidgets.QPushButton(self.gridWidget)
        self.ouvrirGP.setObjectName("ouvrirGP")
        self.gridLayout_2.addWidget(self.ouvrirGP, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.gridWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.closeUI2 = QtWidgets.QPushButton(self.body)
        self.closeUI2.setStyleSheet("color:white;\n"
"background:rgb(255, 64, 47);\n"
"width:100px;\n"
"height:40px;\n"
"border-radius:10px;\n"
"font: 75 10pt \"Rockwell\";")
        self.closeUI2.setObjectName("closeUI2")
        self.verticalLayout_4.addWidget(self.closeUI2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.body)
        self.footer = QtWidgets.QWidget(self.centralwidget)
        self.footer.setStyleSheet("border-top:2px solid white;")
        self.footer.setObjectName("footer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.footer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.footer)
        self.label_7.setStyleSheet("background:rgb(0, 0, 70);\n"
"color:white;\n"
"font-size:14px;\n"
"border:0px solid blue")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.verticalLayout.addWidget(self.footer)
        MainWindow2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "Acceuil"))
        self.label_2.setText(_translate("MainWindow2", "APPAREILLAGE INDUSTRIEL DE MADAGASCAR"))
        self.pushButton_4.setText(_translate("MainWindow2", "Les Opérations Financières"))
        self.pushButton_2.setText(_translate("MainWindow2", "Atelier"))
        self.ouvrirGP.setText(_translate("MainWindow2", "Gestion du Personnel"))
        self.pushButton_3.setText(_translate("MainWindow2", "Les Enegies Renouvelables"))
        self.closeUI2.setText(_translate("MainWindow2", "Fermer"))
        self.label_7.setText(_translate("MainWindow2", "© Hopes-2024"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())
